import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { readFileSync, readdirSync } from 'node:fs';
import { resolve } from 'node:path';

const output = resolve('.validation', 'allure-failure-harness', String(Date.now()));
const child = spawnSync(process.execPath, ['scripts/e2e.mjs', 'run', '--config', 'e2e.evidence.config.ts', '--output', output], { stdio: 'inherit' });
assert.equal(child.status, 1, 'The canary must fail as a test assertion, not pass or crash.');
const report = JSON.parse(readFileSync(resolve(output, 'report.json'), 'utf8'));
assert.equal(report.run.results.length, 1);
assert.equal(report.run.results[0].status, 'failed');
const manifest = JSON.parse(readFileSync(resolve(output, 'allure-results/current.json'), 'utf8'));
assert.equal(manifest.runId, report.run.id);
assert.equal(manifest.resultFiles, 1);
const directory = resolve(output, manifest.resultsDirectory);
const files = readdirSync(directory);
const result = JSON.parse(readFileSync(resolve(directory, files.find(name => name.endsWith('-result.json'))), 'utf8'));
assert.equal(result.status, 'failed');
assert.ok(result.steps.some(step => step.status === 'failed' && step.statusDetails.message.includes('ASSERTION_FAILED')));
assert.equal(result.links[0].url, `${new URL(report.run.results[0].attempts[0].failure.url).origin}/lightning/o/Opportunity/list?evidence=canary`);
for (const name of ['Detailed attempt log', 'Failure URL', 'Screenshot at failure']) assert.ok(result.attachments.some(attachment => attachment.name === name), `Missing ${name}`);
const screenshot = result.attachments.find(attachment => attachment.name === 'Screenshot at failure');
assert.equal(readFileSync(resolve(directory, screenshot.source)).subarray(0, 8).toString('hex'), '89504e470d0a1a0a');
const log = JSON.parse(readFileSync(resolve(directory, result.attachments.find(attachment => attachment.name === 'Detailed attempt log').source), 'utf8'));
assert.ok(log.steps.length > 3 && log.error.code === 'ASSERTION_FAILED');
for (const name of files.filter(name => /\.(json|txt|properties)$/.test(name))) assert.doesNotMatch(readFileSync(resolve(directory, name), 'utf8'), /synthetic-ui-(otp|checksum)-canary/);
console.log('OK | Failed assertion, detailed log, exact failure URL and automatic PNG verified in Allure.');
console.log(`Evidence harness: ${output}`);
